# Generated by Django 5.2.6 on 2025-11-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shortLinks',
            new_name='ShortURL',
        ),
    ]
